# Homebrew packages to install
# This file defines all the tools that should be installed via Homebrew

packages:
  # Core development tools
  - direnv
  - just
  - gh  # GitHub CLI
  
  # Text processing and search
  - jq
  - fzf
  - ripgrep
  - bat
  
  # Version management
  - git
  - git-lfs
  
  # Development utilities
  - tree
  - htop
  - tmux
  - neovim  # Modern vim editor with better defaults
  
  # Container tools (optional)
  # - docker
  # - docker-compose
  
  # Language runtimes (optional)
  # - node
  # - go
  # - rustup-init
  
  # Database tools (optional)
  # - postgresql
  # - redis 